In [1]:
import numpy as np

In [3]:
x=[[1,2],[3,4]]
s=0
for i in x:
    s+=sum(i)
print(s)

10


In [5]:
nx=np.array(x)
print(nx.sum())
print(nx.min())
print(nx.max())

10
1
4


In [6]:
type(nx)

numpy.ndarray

In [8]:
print(nx.shape)
print(nx.size)
print(nx.dtype)

(2, 2)
4
int64


In [9]:
a=[[1,2,7],[3,4,5],[6,7,4]]
na=np.array(a)


## function to create matrix
- arange: create a range of numbers
- linespace: create a matrix of specified number of elements
- ones
- zeros
- random.randint: create a matrix of random integers
- random.rand: create a matrix of random floats
- diag

In [16]:
a=np.arange(1,40)
print(a)

b=np.arange(1,4,.02).size
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
150


In [17]:
np.linspace(2,24,10)

array([ 2.        ,  4.44444444,  6.88888889,  9.33333333, 11.77777778,
       14.22222222, 16.66666667, 19.11111111, 21.55555556, 24.        ])

In [18]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [26]:
np.ones([4,4]).dtype=int

In [24]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [28]:
np.random.randint(1,100,5)

array([16, 81, 90, 83, 97], dtype=int32)

In [32]:
np.random.randint(2,3,(5,5,5))

array([[[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]], dtype=int32)

In [33]:
np.random.rand(1,10,2)

array([[[0.09997034, 0.94731077],
        [0.80922913, 0.84099201],
        [0.79440664, 0.72220321],
        [0.10462284, 0.99680758],
        [0.37195062, 0.65767319],
        [0.0465829 , 0.91192577],
        [0.04956588, 0.69728321],
        [0.13706402, 0.49615725],
        [0.96946126, 0.81723685],
        [0.0110201 , 0.48347649]]])

In [35]:
np.set_printoptions(precision=3)
np.random.rand(10,5)

array([[0.173, 0.14 , 0.801, 0.655, 0.584],
       [0.746, 0.716, 0.429, 0.314, 0.044],
       [0.772, 0.154, 0.816, 0.472, 0.441],
       [0.037, 0.456, 0.477, 0.379, 0.374],
       [0.921, 0.099, 0.059, 0.398, 0.581],
       [0.129, 0.366, 0.565, 0.79 , 0.672],
       [0.194, 0.329, 0.202, 0.307, 0.857],
       [0.613, 0.589, 0.269, 0.189, 0.285],
       [0.358, 0.852, 0.55 , 0.804, 0.14 ],
       [0.016, 0.775, 0.116, 0.766, 0.766]])

In [36]:
x=[1,2,3,4,5]
np.diag(x)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [40]:
# reshape
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
a=np.linspace(1,5,25).reshape(5,5)

In [44]:
a.flatten()

array([1.   , 1.167, 1.333, 1.5  , 1.667, 1.833, 2.   , 2.167, 2.333,
       2.5  , 2.667, 2.833, 3.   , 3.167, 3.333, 3.5  , 3.667, 3.833,
       4.   , 4.167, 4.333, 4.5  , 4.667, 4.833, 5.   ])

In [45]:
a.transpose()

array([[1.   , 1.833, 2.667, 3.5  , 4.333],
       [1.167, 2.   , 2.833, 3.667, 4.5  ],
       [1.333, 2.167, 3.   , 3.833, 4.667],
       [1.5  , 2.333, 3.167, 4.   , 4.833],
       [1.667, 2.5  , 3.333, 4.167, 5.   ]])

In [48]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))
print(a)
print(b)

[[9 3 7]
 [2 1 6]
 [3 8 3]]
[[3 9 5]
 [6 8 7]
 [6 3 4]]


In [47]:
a+b

array([[ 6,  9, 11],
       [ 7,  9, 10],
       [11, 10,  8]], dtype=int32)

In [49]:
a*b

array([[27, 27, 35],
       [12,  8, 42],
       [18, 24, 12]], dtype=int32)

In [50]:
a-b

array([[ 6, -6,  2],
       [-4, -7, -1],
       [-3,  5, -1]], dtype=int32)

In [51]:
a.dot(b) #matrix multiplication

array([[ 87, 126,  94],
       [ 48,  44,  41],
       [ 75, 100,  83]], dtype=int32)

In [52]:
a+10

array([[19, 13, 17],
       [12, 11, 16],
       [13, 18, 13]], dtype=int32)

### stats

In [53]:
print(a.mean())

4.666666666666667


In [54]:
print(a.mean(axis=0))
print(a.mean(axis=1))

[4.667 4.    5.333]
[6.333 3.    4.667]


In [55]:
print(a.sum())
print(a.sum(axis=0))   # column wise
print(a.sum(axis=1))   # row wise mean 

42
[14 12 16]
[19  9 14]


In [56]:
np.sin(a)

array([[ 0.412,  0.141,  0.657],
       [ 0.909,  0.841, -0.279],
       [ 0.141,  0.989,  0.141]])

In [57]:
np.cos(b)

array([[-0.99 , -0.911,  0.284],
       [ 0.96 , -0.146,  0.754],
       [ 0.96 , -0.99 , -0.654]])

In [58]:
print(np.exp(a))
print(np.square(a))
print(np.sqrt(a))

[[8.103e+03 2.009e+01 1.097e+03]
 [7.389e+00 2.718e+00 4.034e+02]
 [2.009e+01 2.981e+03 2.009e+01]]
[[81  9 49]
 [ 4  1 36]
 [ 9 64  9]]
[[3.    1.732 2.646]
 [1.414 1.    2.449]
 [1.732 2.828 1.732]]


In [59]:
c=np.random.randint(1,100,(3,3))
print(c)

[[12 29 63]
 [ 4 96 11]
 [19 18 41]]


In [61]:
print(c.max())
print(c.argmax())
print(c.min())
print(c.argmin())

96
4
4
3
